name: "CI"

on:
  pull_request:
    types: ["opened", "reopened", "synchronize", "ready_for_review"]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

permissions: read-all

jobs:
  config:
    runs-on: ["windows-latest"]
    timeout-minutes: 10
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v5.0.0
        with:
          global-json-file: "global.json"

      - uses: nuget/setup-nuget@v2.0.1
        with:
          nuget-version: "latest"

      - name: "Pack"
        run: nuget pack Kiruyuto.DotNet.Config.nuspec -ForceEnglishOutput -Version 0.0.1

      - name: "Ensure scripts work"
        shell: pwsh
        run: |
          ./PackAndRegister.ps1
          ./RemovePackageAndUnregisterFeed.ps1