name: "CI"

on:
  pull_request:
    types: ["opened", "reopened", "synchronize", "ready_for_review"]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

permissions: read-all

jobs:
  config:
    runs-on: ["ubuntu-latest"]
    timeout-minutes: 10
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Setup .NET"
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          global-json-file: "global.json"

      - name: "Pack"
        run: dotnet pack Kiruyuto.DotNet.Config/Kiruyuto.DotNet.Config.csproj -c Release -o . -p:PackageVersion=0.0.1